backend development 2.0.0/backend/models.py
from backend import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(80), nullable=False)
    # filename = db.Column(db.String(300))
    file = db.Column(db.LargeBinary)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}', '{self.password}')"

backend development 2.0.0/backend/dashboard/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileField, FileAllowed
from wtforms import SubmitField
from wtforms import ValidationError


class uploadfile(FlaskForm):
    data = FileField(validators=[FileRequired(),FileAllowed(['csv', 'Please Upload csv only!'])])
    submit = SubmitField('Submit')
    

backend development 2.0.0/backend/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, ValidationError
from wtforms.validators import DataRequired, Length, Email, EqualTo
from backend.models import User


class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)], render_kw={"placeholder": "Username"})
    email = StringField('Email',
                        validators=[DataRequired(), Email()], render_kw={"placeholder": "email"})
    password = PasswordField('Password', validators=[DataRequired(), Length(min=7, max=20)], render_kw={"placeholder": "password"})
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')], render_kw={"placeholder": "confirm password"})
    submit = SubmitField('Sign Up')
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()], render_kw={"placeholder": "email"})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={"placeholder": "password"})
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')



    

backend development 2.0.0/backend/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from backend.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    
    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    from backend.users.routes import users
    from backend.dashboard.routes import dashboards
    from backend.main.routes import main
    from backend.errors.handlers import errors
    app.register_blueprint(users)
    app.register_blueprint(main)
    app.register_blueprint(errors)
    app.register_blueprint(dashboards)

    return app

backend development 2.0.0/backend/dashboard/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, request
from backend import  db, bcrypt
from backend.dashboard.forms import uploadfile
from backend.models import User
from flask_login import current_user, login_required
from wtforms import ValidationError
from backend.dashboard.utils import show_data



dashboards = Blueprint('dashboards', __name__)



@dashboards.route('/dashboard', methods=['POST','GET'])
@login_required
def dashboard():
    form = uploadfile()
    if form.validate_on_submit():
        file =  request.files['data']
        user = User.query.filter_by(username=current_user.username).first()
        user.file = file.read()
        db.session.commit()
        return redirect(url_for('dashboards.dashboard'))
    else:
        dats = User.query.filter_by(username=current_user.username).first().file
        if dats:
            mydata = show_data(dats)
            if request.method == 'POST':
                user_input = request.form
                print(user_input)
                if user_input['input_value'] == 'show_data_shape':
                    output = show_data.df.shape
                return render_template('dashboard/dashboard.html', form=form,headings=mydata[0], data=mydata[1], output= output)
            return render_template('dashboard/dashboard.html', form=form,  headings=mydata[0], data=mydata[1])
    return render_template('dashboard/dashboard.html', form=form)
    


@dashboards.route('/machine_learning')
@login_required
def ml():
    return render_template('dashboard/machine_learning.html')

@dashboards.route('/AboutUs')
@login_required
def about():
    return render_template('dashboard/aboutus.html')

backend development 2.0.0/backend/main/routes.py
from flask import redirect, url_for, render_template, Blueprint
from flask_login import current_user

main = Blueprint('main', __name__)

@main.route('/')
def index():
    if current_user.is_authenticated:
        return redirect(url_for('dashboards.dashboard'))
    return render_template('index.html')

backend development 2.0.0/backend/users/routes.py
from flask import Blueprint, session
from flask import render_template, redirect, url_for, flash
from backend import  db, bcrypt
from backend.users.forms import RegistrationForm, LoginForm
from backend.models import User

from flask_login import login_user, current_user, logout_user, login_required



users = Blueprint('users', __name__)



@users.route('/signup', methods=['POST', 'GET'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('dsahboards.dashboard'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.email.data}, Now you can login with your account details', 'success')
        return redirect(url_for('users.login'))
    return render_template('auth/signup.html', form=form)



@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('dashboards.dashboard'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            session.permanent = True
            return redirect(url_for('dashboards.dashboard'))
        else:
            flash(f'Login denied, Incorrect email or password!', 'danger')
    return render_template('auth/login.html', form=form)

    

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

backend development 2.0.0/backend/templates/dashboard/aboutus.html
{% extends "layouts/layout.html" %}
{% set active_page = "about" %}
{% block content %}

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magnam a numquam debitis reiciendis quam, molestias dolore cupiditate, quidem architecto saepe hic dolores ea, nulla atque. Vel animi eligendi illo repudiandae.</p>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora nobis est nisi eligendi commodi quod, accusantium sed recusandae dignissimos et labore sapiente minus soluta suscipit magnam natus voluptatibus fuga laboriosam.</p>

{% endblock content %}

backend development 2.0.0/backend/templates/dashboard/dashboard.html
{% extends "layouts/layout.html" %}
{% set active_page = "dashboard" %}
{% block content %}
<div id="show-this"></div>
{% if headings is not defined %}
    <p>Upload your data to start working with our tools</p>
{% endif %}
<!-- <h1>{{ current_user.username }}</h1> -->

<form action="" method="POST" enctype="multipart/form-data" class="mb-4">
    {{ form.hidden_tag() }}
    <fieldset>
        <div>
            {% if form.data.errors %}
                {% for error in form.data.errors %}
                    <label class="text-danger mt-2">{{ error }}</label> <br>
                {% endfor %}
                {{ form.data(class="btn-sm border") }}
                {{ form.submit(class="btn-sm mt-3") }}
            {% else %}
                {{ form.data(class="btn-sm border") }}
                {{ form.submit(class="btn-sm mt-3") }}
            {% endif %}
        </div>
    </fieldset>
</form>


<!-- dataset upload file -->
<div style=" overflow-x: auto;">
    <table style="font-size: small;" class="table table-bordered table-hover table-condensed">

        <tr>
          {% for header in headings %}
          <th>{{ header }}</th>
          {% endfor %}
        </tr>
    
        {% for row in data %}
        <tr>
          {% for cell in row %}
          <td>{{ cell }}</td>
          {% endfor %}
        </tr>
        {% endfor %}
      </table>
</div>

<!-- section working with dataset -->
<div class="mt-4 section-working-with-data ">
    <h2>Clean My dataset</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum vitae aut hic sit iste quo assumenda. Itaque officia obcaecati non sequi! Qui, voluptatum adipisci? Eaque, officiis! Dolorum enim numquam voluptate.</p>
    <form action="" method="post">
        <select name="" id="">
            {% for header in headings %}
            <option value="{{ header }}">{{ header }}</option>
            {% endfor %}
        </select>
    </form>
    <div class="row">
        <div class="col-auto">
            <div class="tree"  style="height: 400px; overflow: auto;">
                <form id="my_form" method="POST" action="">
                    <ul>
                        <li><span><a style="color:#000; text-decoration:none;">Web</a></span>
                            <div id="Web">
                                <ul>
                                    <!-- first element -->
                                    <li><span><a style="color:#000; text-decoration:none;">work 1</a></span>
                                        <ul>
                                            <div>
                                                <li><span>
                                                        <a href="#!">
                                                            <input style="display: none;" onchange='this.form.submit();' type="radio" id="html" 
                                                            name="input_value" value="show_data_shape">
                                                            <label data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>" for="html">Shape of data</label>

                                                        </a>
                                                    </span></li>
                                            </div>
                                        </ul>
                                    </li>
    
                                    <!-- second element -->
                                    <li><span><a style="color:#000; text-decoration:none;">work 2</a></span>
                                        <ul>
                                            <div>
                                                <li><span>
                                                        <a href="{{url_for('dashboards.dashboard')}}">
                                                            here goes the work
                                                        </a>
                                                    </span></li>
                                            </div>
                                        </ul>
                                    </li>
    
                                    <!-- third element -->
                                    <li><span><a style="color:#000; text-decoration:none;">work 3</a></span>
                                        <ul>
                                            <div>
                                                <li><span><a style="color:#000; text-decoration:none;"
                                                            data-toggle="collapse" href="#folder1"
                                                            aria-expanded="false" aria-controls="folder1"><i
                                                                class="collapsed"></i>Folder 1</a></span>
                                                    <ul>
                                                        <div id="folder1" class="collapse">
    
    
                                                            <li><span><a style="color:#000; text-decoration:none;"
                                                                        data-toggle="collapse" href="#foldersub"
                                                                        aria-expanded="false"
                                                                        aria-controls="foldersub"><i
                                                                            class="collapsed"></i>work 3 folder 1
                                                                        subfolder</a></span>
                                                                <ul>
                                                                    <div id="foldersub" class="collapse">
                                                                        <li><span>
                                                                                <a href="#!">
                                                                                    here goes the work
                                                                                </a>
                                                                            </span></li>
                                                                        <li><span>
                                                                                <a href="#!">
                                                                                    here goes the work
                                                                                </a>
                                                                            </span></li>
                                                                        <li><span>
                                                                                <a href="#!">
                                                                                    here goes the work
                                                                                </a>
                                                                            </span></li>
                                                                    </div>
                                                                </ul>
                                                            </li>
                                                        </div>
                                                    </ul>
                                                </li>
    
                                                <li><span><a style="color:#000; text-decoration:none;"
                                                            data-toggle="collapse" href="#folder2"
                                                            aria-expanded="false" aria-controls="folder2"><i
                                                                class="collapsed"></i>Folder 2</a></span>
                                                    <ul>
                                                        <div id="folder2" class="collapse">
                                                            <li><span>
                                                                    <a href="#!">
                                                                        here goes the work
                                                                    </a>
                                                                </span></li>
                                                            <li><span>
                                                                    <a href="#!">
                                                                        here goes the work
                                                                    </a>
                                                                </span></li>
                                                            <li><span>
                                                                    <a href="#!">
                                                                        here goes the work
                                                                    </a>
                                                                </span></li>
                                                        </div>
                                                    </ul>
                                                </li>
    
    
                                                <li><span><a style="color:#000; text-decoration:none;"
                                                            data-toggle="collapse" href="#folder3"
                                                            aria-expanded="false" aria-controls="folder3"><i
                                                                class="collapsed"><i class="fas fa-folder"></i></i>
                                                            <i class="expanded"><i
                                                                    class="far fa-folder-open"></i></i> Folder
                                                            3</a></span>
                                                    <ul>
                                                        <div id="folder3" class="collapse">
                                                            <li><span><i class="far fa-file"></i><a href="#!">
                                                                        Link</a></span>
                                                            </li>
                                                        </div>
                                                    </ul>
                                                </li>
    
                                                <li><span><i class="far fa-file"></i><a href="#!"> Link</a></span>
                                                </li>
    
                                            </div>
                                        </ul>
                                    </li>
    
    
                                    <li><span><a href="#!"> Link 2</a></span></li>
    
    
    
                                </ul>
                            </div>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
        <div class="col" style="height: 400px;  overflow: auto; width: 500px; padding: 0px; margin: 0px;">
            <div class="vertical-center-me w-100 text-center">
                {% if output %}
                <p>Number of rows are: {{output[0]}}</p>
                <p>Number of columns are:  {{output[1]}}</p>
                {% else %}
                <p>Output is going to show here once you select any of the box from left given tree.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>



<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id, asperiores quibusdam. Optio nam, ex tempore consequuntur illo perspiciatis minima repudiandae, autem earum unde deleniti doloribus quibusdam, nisi facere consequatur molestias.</p>

{% endblock content %}

backend development 2.0.0/backend/templates/dashboard/machine_learning.html
{% extends "layouts/layout.html" %}
{% set active_page = "ml" %}
{% block content %}

<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magnam a numquam debitis reiciendis quam, molestias dolore cupiditate, quidem architecto saepe hic dolores ea, nulla atque. Vel animi eligendi illo repudiandae.</p>
<h1>{{ current_user.username }}</h1>
{% endblock content %}

backend development 2.0.0/backend/templates/index.html
{% extends "layouts/layout.html" %}
{% set active_page = "index" %}
{% block content %}

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A, consequuntur explicabo. Dignissimos dolor, fugiat illo iure provident nostrum voluptatem commodi? Eius aut saepe numquam nisi delectus temporibus repellat doloribus eum!</p>

{% endblock content %}

backend development 2.0.0/backend/templates/layouts/layout.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='stylesheets/style.css') }}">

    <title>Nasir</title>
</head>

<body>
    <div class="container">
        <nav class="bg-white sticky-top container p-0 pt-4">
            <h3>Nasir.com</h3>
            {% if current_user.is_authenticated %}
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'dashboard' else '' }}"
                    href="{{url_for('dashboards.dashboard')}}">Dashboard {{ '(active)' if active_page == 'dashboard' else '' }}</a> |
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'ml' else '' }}"
                    href="{{url_for('dashboards.ml')}}">Machine Learning {{ '(active)' if active_page == 'ml' else '' }}</a> |
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'about' else '' }}"
                    href="{{url_for('dashboards.about')}}">About Us {{ '(active)' if active_page == 'about' else '' }}</a> |
                <a class="" href="{{url_for('users.logout')}}">Logout {{ '(active)' if active_page == 'signup' else '' }}</a>
            {% else %}
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'index' else '' }}"
                href="{{url_for('main.index')}}">Home {{ '(active)' if active_page == 'index' else '' }}</a> |
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'login' else '' }}"
                href="{{url_for('users.login')}}">Log In {{ '(active)' if active_page == 'login' else '' }}</a> |
                <a class="{{ 'text-muted text-decoration-none remove-cursor' if active_page == 'signup' else '' }}"
                href="{{url_for('users.signup')}}">Sign Up {{ '(active)' if active_page == 'signup' else '' }}</a>
            {% endif %}
            <hr>
        </nav>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <!-- my own person script -->
    <script src="{{ url_for('static',filename='scripts/main.js') }}"></script>
</body>

</html>